### ISSUE TITLE
Add a new language and ensure the app functions correctly. 

### ISSUE THREAD

**Issue by newtewt** [medic/medic-release-testing#60]
User:  Restricted User
Site: Standard Config
Platform: Desktop With Chrome
Test Steps:
As an admin add a new custom language to the application. 
Log in as a restricted user that has the custom language as there language.
Ensure the app loads. EX: Tasks are showing, targets are calculating, reports are visible, and people are enabled.

**Comment by ngaruko** [comment]
LGTM.
But there is a [small issue](https://github.com/medic/translation-checker/issues/2) with non-ISO languages (ISO-639-1). Not a blocker.

**Comment by ngaruko** [comment]
This has been [automated](https://github.com/medic/cht-core/pull/7078)

**Comment by ngaruko** [comment]
Already [automated](https://github.com/medic/cht-core/pull/7078)
