### ISSUE TITLE
Add custom places and types using configurable hierarchy

### ISSUE THREAD

**Issue by newtewt** [medic/medic-release-testing#61]
User: Restricted User and Online user
Site: Standard Config
Platform: Desktop With Chrome
Test Steps:
Add a custom places and persons to the app settings. Using the guide [here.](https://github.com/medic/medic-docs/blob/master/configuration/app-settings.md#configuring-the-contact-hierarchy)
Create custom types and persons. 
Ensure you can create reports, tasks, for these types.

**Comment by meghna-khemka** [comment]
Issue working fine
![image](https://user-images.githubusercontent.com/84743933/125500680-b898ceea-dd78-4777-8709-f2a12b9ba5d4.png)
