### ISSUE TITLE
3.9 gamma.dev wipe

### ISSUE THREAD

**Issue by newtewt** [medic/medic-release-testing#85]
For 3.9.0 testing we need to wipe https://gamma.dev.medicmobile.org/ and start fresh. No idea what's on there now.

**Comment by nomulex** [comment]
This has been implemented along  with https://gamma-b.dev.medicmobile.org  and https://gamma-cht.dev.medicmobile.org .  This and gamma d are fresh instances while https://gamma-cht.dev.medicmobile.org has got cht data. ^^ @newtewt , @brad1905 , @ngaruko

**Comment by nomulex** [comment]
Credentials in 1password
