### ISSUE TITLE
Group release testing tasks that are of the same flow.

### ISSUE THREAD

**Issue by newtewt** [medic/medic-release-testing#89]
When moving to github we lost release test cases that were of the same workflow. Need to find a way to group test cases together to get this workflow testing back.  My initial thought is to create a label or maybe add a ` Workflow:` section to the github ticket.  

EX: Create new person
Register pregnancy
Register delivery 
Verify has been created into 3 or 4 test cases. This isn't necessarily bad but to make things a little more efficient. Having these test cases that represent a workflow would make testing a little bit faster.

**Comment by brad1905** [comment]
A label will filter cards to show the progress on testing the workflow and allow us to see which workflows have tests. Perhaps a label like: "workflow-pregnancy".

**Comment by newtewt** [comment]
Another thought, get rid of the excess cards and condense to one.

**Comment by ngaruko** [comment]
Created new issues as workflows with details in description (need a lot of editing/updating). 
Remove `Release Test` labels from the small steps that are now included in the newly created issues.
Please have look and see if I missed anything @newtewt @brad1905 .

**Comment by newtewt** [comment]
@ngaruko  solid! I think as we pick one up we can edit/update as we test.  I think it might also be beneficial if we add templates to the project so when new issues are created some of the details are already there. I can put a issue in for our backlog. 

I like this condensed approach. 

Can you clarify what this one is for?

https://github.com/medic/medic-release-testing/issues/95

**Comment by newtewt** [comment]
@ngaruko  can this be closed?
