### ISSUE TITLE
Pregnancy Workflow (standard)

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-release-testing#97]
1. Add a new woman of childbearing age to your area using the add person form in the web app
2. Make sure the Medic ID field gets populated (you may have to wait briefly for Sentinel to generate the ID)
3. Register a pregnancy for this woman using the web app
4. Make sure the condition card for pregnancy appears
5. Check the record in Reports to make sure the appropriate SMS schedule is generated
6. Check the targets page to make sure the pregnancy registration was counted (restricted users only)
7. Do a pregnancy visit for the woman you just registered using the web app
8. Make sure the condition card updates to reflect the visit
9. Check the record in Reports to make sure the appropriate outgoing SMS is generated
10. Do a pregnancy visit for the woman you just registered using SMS (V form) via Medic Reporter. Make sure you put the phone number of your area in the “Sent From” field on the right.
11. Make sure the condition card updates to reflect the visit
12. Check the record in Reports to make sure the appropriate outgoing SMS is generated
13. Do a delivery report (facility delivery) for the woman you registered using the web app
14. Make sure that the pregnancy condition card disappears
15. Make sure that the postnatal care condition card appears
16. Make sure that the past pregnancies condition card appears
17. Check the record in Reports to make sure the appropriate SMS schedule is generated (if you included a delivery date)
18. Check the targets page to make sure the deliveries with 1+ visit widget updates (restricted users only)
19. Add a new person by using the N form via Medic Reporter. Make sure you put the phone number of your area in the “Sent From” field on the right
20. Make sure that the Medic ID field gets populated
21. Register a pregnancy for this woman using SMS (P form)
22. Make sure the condition card for pregnancy appears
23. Check the record in Reports to make sure the appropriate SMS schedule is generated
24. Check the targets page to make sure the pregnancy registration was counted (restricted users only)
25. Do a pregnancy visit for the woman you just registered using the web app
26. Make sure the condition card updates to reflect the visit
27. Check the record in Reports to make sure the appropriate outgoing SMS is generated
28. Do a pregnancy visit for the woman you just registered using SMS (V form) via Medic Reporter. Make sure you put the phone number of your area in the “Sent From” field on the right.
29. Make sure the condition card updates to reflect the visit
30. Check the record in Reports to make sure the appropriate outgoing SMS is generated
31. Do a delivery report (facility delivery) for the woman you registered using SMS (D form)
32. Make sure that the pregnancy condition card disappears
33. Make sure that the postnatal care condition card appears
34. Make sure that the past pregnancies condition card appears
35. Check the record in Reports to make sure the appropriate SMS schedule is generated (if you included days since delivery, there should be a PNC schedule)
36. Check the targets page to make sure the deliveries with 1+ visit widget updates (restricted users only)

**Comment by tatilepizs** [comment]
### **Pregnancy Workflow for "Woman1" - Created using webapp**

**User:**  CHW
**Config:** Standard
 **Environment:** gamma.dev
**Platform:** WebApp 
**Browser:** Chrome

- New woman of childbearing age created. All her information its populated in the card.
![image](https://user-images.githubusercontent.com/94494491/152004197-ec834a8f-975d-465b-9c40-a9a726720a11.png)

- Pregnancy registered. 
![image](https://user-images.githubusercontent.com/94494491/152004535-c1cf6b13-a1f1-4482-acff-9dd823c3576c.png)

- Record in reports created.
![image](https://user-images.githubusercontent.com/94494491/152004690-c61dfa2f-9df9-49bb-8917-607253d736d3.png)

- Targets updated.
![image](https://user-images.githubusercontent.com/94494491/152004816-5298344a-91b6-48a4-9443-3ed1f6c2a574.png)

- Pregnancy visit created
![image](https://user-images.githubusercontent.com/94494491/152005995-553e30d9-c547-436b-a1e2-0ce28cc152a2.png)

- Record in reports created
![image](https://user-images.githubusercontent.com/94494491/152006046-40058ef0-8460-47f8-b314-743be577a492.png)

- Pregnancy visit using SMS (V form) created.
![image](https://user-images.githubusercontent.com/94494491/152007829-6933c205-489b-40c9-9b7d-0b31e4b65df1.png)

![image](https://user-images.githubusercontent.com/94494491/152008105-1dfc291b-7717-490e-b570-7d80aca0dd80.png)

- Record in Reports created
![image](https://user-images.githubusercontent.com/94494491/152008280-8816bd37-ece5-4487-a5a1-ca86c7a79a0e.png)

- Delivery report (facility delivery) created
![image](https://user-images.githubusercontent.com/94494491/152009708-4e2f711d-136f-483e-a489-f9a5571f6aa2.png)

- Make sure that the postnatal care condition card appears ????

- Record in reports created.
![image](https://user-images.githubusercontent.com/94494491/152009889-e3f38209-bd60-4466-81cb-2c813f174f0d.png)

- Targets updated.
![image](https://user-images.githubusercontent.com/94494491/152010020-ee23f120-be73-483c-aa23-93423c613aa6.png)

**Comment by tatilepizs** [comment]
### **Pregnancy Workflow for "Woman2" - Created using SMS**

**User:** CHW
**Config:** Standard
 **Environment:** gamma.dev
**Platform:** WebApp 
**Browser:** Chrome

- New person created (N form).
![image](https://user-images.githubusercontent.com/94494491/152058824-5a92433c-3704-4687-abc5-a38808ce14ba.png)
![image](https://user-images.githubusercontent.com/94494491/152058908-6bbc1fe6-674a-4ca2-8221-76d9d168730f.png)

- Pregnancy registered (P form)
![image](https://user-images.githubusercontent.com/94494491/152060407-88f1fbd4-1c36-41db-95ab-d779f9cf7a37.png)

- Record in reports created.
![image](https://user-images.githubusercontent.com/94494491/152060513-5db4b8e1-e34a-40b6-b29d-a631e7e42954.png)

- Targets updated
![image](https://user-images.githubusercontent.com/94494491/152060814-48fdd969-8028-430d-9eb7-b80067c0e197.png)

- Pregnancy visit created (web app)
![image](https://user-images.githubusercontent.com/94494491/152061011-8bc31b90-6ca5-4f1b-81ef-ca6700d1b4e6.png)

- Record in reports created.
![image](https://user-images.githubusercontent.com/94494491/152061145-2773e8d5-2959-421f-9d6f-166bc6d7d952.png)

- Pregnancy visit created (V form) 
![image](https://user-images.githubusercontent.com/94494491/152061487-2c7ae563-4f43-4874-87cd-004d237c5f0a.png)

- Record in reports created.
![image](https://user-images.githubusercontent.com/94494491/152061580-3253ff55-3e0c-441f-a738-cb37cd7d67d3.png)

- Delivery report (facility delivery) created (D form).
![image](https://user-images.githubusercontent.com/94494491/152062316-169bfebd-495b-43d3-9f74-8c5fbfcb77af.png)

- Make sure that the postnatal care condition card appears ???

- Record in reports created.
![image](https://user-images.githubusercontent.com/94494491/152062537-5f9aacdf-394a-4e6f-9996-9ba026a3eb8c.png)

- Targets updated.
![image](https://user-images.githubusercontent.com/94494491/152062651-639d7268-5ba4-42f1-9c80-2518f7856068.png)

**Comment by tatilepizs** [comment]
### **Pregnancy Workflow for "Woman1" - Created using webapp**

**User:** CHW
**Config:** Standard
 **Environment:** gamma-cht
**Platform:** WebApp 
**Browser:** Chrome

<details>
<summary>New woman of childbearing age created. All her information its populated in the card.</summary>

![image](https://user-images.githubusercontent.com/94494491/164538005-180016cc-e669-45e7-a4cd-ed9acb06bc0d.png)

</details>

<details>
<summary>Pregnancy registered.</summary>

![image](https://user-images.githubusercontent.com/94494491/164538638-4408071f-d62f-467a-aa8a-ba8b32ba485d.png)

</details>

<details>
<summary>Record in reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/164538777-944073a8-fab3-4196-81e2-471dcad9c106.png)

</details>

<details>
<summary>Targets updated.</summary>

![image](https://user-images.githubusercontent.com/94494491/164538900-59c6501d-dbc0-448c-98bb-413c00259711.png)

</details>

<details>
<summary>Pregnancy visit created.</summary>

![image](https://user-images.githubusercontent.com/94494491/164539218-e94d649e-6b68-4e60-9e72-63a7b78cb8cf.png)

</details>

<details>
<summary>Record in reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/164539373-f612ef5f-4d7d-4c96-9239-87bece5e5596.png)

</details>

<details>
<summary>Pregnancy visit using SMS (V form) created.</summary>

![image](https://user-images.githubusercontent.com/94494491/164540200-73f0eefb-7aa9-4d39-bead-c6330e881b38.png)
![image](https://user-images.githubusercontent.com/94494491/164540255-fb5a648b-0b8d-4002-b328-e87f4c990328.png)

</details>

<details>
<summary>Record in Reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/164540428-86495e1e-52ee-412e-8414-ed552564b90c.png)

</details>

<details>
<summary>Delivery report (facility delivery) created.</summary>

![image](https://user-images.githubusercontent.com/94494491/164540905-0873e03c-b9d7-4573-bb65-8effb5bd3e86.png)

</details>

<details>
<summary>Record in reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/164541355-3cf6dde7-ceb9-4369-acb0-21842d35f44b.png)

</details>

<details>
<summary>Targets updated.</summary>

![image](https://user-images.githubusercontent.com/94494491/164541838-c869d280-afe1-499e-855c-1872073fee0d.png)

</details>

**_________________________________________________________________________________**

### **Pregnancy Workflow for "Woman2" - Created using SMS**

**User:** CHW
**Config:** Standard
 **Environment:** gamma-cht
**Platform:** WebApp 
**Browser:** Chrome

<details>
<summary>New person created (N form).</summary>

![image](https://user-images.githubusercontent.com/94494491/164546311-75eb5f9f-8734-4d1e-9b33-8ed637791ca2.png)
![image](https://user-images.githubusercontent.com/94494491/164546374-31537f11-cfa3-4b30-9b39-4b92c66acdbd.png)
![image](https://user-images.githubusercontent.com/94494491/164546413-2785f5bf-c2dc-4d51-818d-80091aff314b.png)

</details>

<details>
<summary>Pregnancy registered (P form).</summary>

![image](https://user-images.githubusercontent.com/94494491/164546539-1b1aee58-d80c-463d-b699-8fc611eaff6e.png)
![image](https://user-images.githubusercontent.com/94494491/164546623-81cbbbdf-aa8f-4f28-9794-dd5714a26d52.png)

</details>

<details>
<summary>Record in reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/164546845-3063e155-e50d-490d-91ba-2fda93a75478.png)

</details>

<details>
<summary>Targets updated</summary>

![image](https://user-images.githubusercontent.com/94494491/164546806-a349acb6-0639-4f07-9bb3-f972003cf0b9.png)

</details>

<details>
<summary>Pregnancy visit created (web app).</summary>

![image](https://user-images.githubusercontent.com/94494491/164547086-652283ac-fb1c-403a-aa2b-c2b8efcc922b.png)

</details>

<details>
<summary>Record in reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/164547219-797aaff9-e025-4620-8148-a28172271579.png)

</details>

<details>
<summary>Pregnancy visit created (V form).</summary>

![image](https://user-images.githubusercontent.com/94494491/164547421-d261df8a-68e1-4d24-9334-16a47dbaeb03.png)
![image](https://user-images.githubusercontent.com/94494491/164547489-e92bd650-e170-4c83-881b-970146f96022.png)

</details>

<details>
<summary>Record in reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/164547638-81e9ba3f-7166-46d7-b090-4e1b139faadc.png)

</details>

<details>
<summary>Delivery report (facility delivery) created (D form).</summary>

![image](https://user-images.githubusercontent.com/94494491/164547934-d738ffbb-45e8-4bef-80e9-94ac4a203172.png)
![image](https://user-images.githubusercontent.com/94494491/164548033-395668f9-e44c-44d1-9531-2f647585f9e1.png)

</details>

<details>
<summary>Record in reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/164548197-2dc836cb-8fd6-40f1-910d-979b000b8428.png)

</details>

<details>
<summary>Targets updated.</summary>

![image](https://user-images.githubusercontent.com/94494491/164548432-32a0394c-bece-426c-8403-0b3208856c3d.png)

</details>

**Comment by tatilepizs** [comment]
### **Pregnancy Workflow for "Tiana" - Created using webapp**

**User:** CHW
**Config:** Standard
 **Environment:** gamma-cht
**Platform:** WebApp 
**Browser:** Chrome

<details>
<summary>New woman of childbearing age created. All her information is populated on the card.</summary>

![image](https://user-images.githubusercontent.com/94494491/181592054-179e2845-2102-4535-95e0-79df5c1e4076.png)

</details>

<details>
<summary>Pregnancy registered.</summary>

![image](https://user-images.githubusercontent.com/94494491/181592222-043bf0e6-2666-4d17-8b30-cf076545544a.png)

</details>

<details>
<summary>Record in reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/181592377-3ee59861-4a21-4a61-b61f-dec212b3a77a.png)

</details>

<details>
<summary>Targets updated.</summary>

![image](https://user-images.githubusercontent.com/94494491/181592492-d6ab63cc-3805-4fd6-8774-60353ce92f77.png)

</details>

<details>
<summary>Pregnancy visit created.</summary>

![image](https://user-images.githubusercontent.com/94494491/181592792-912c4f85-3e1f-4399-b54b-305a58afaad8.png)

</details>

<details>
<summary>Record in reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/181592988-fe3c6104-8b66-4f55-b2b6-e09e726c7006.png)

</details>

<details>
<summary>Pregnancy visit using SMS (V form) created.</summary>

![image](https://user-images.githubusercontent.com/94494491/181593385-43e9786b-642c-4cc0-b14b-a72f29143986.png)
![image](https://user-images.githubusercontent.com/94494491/181593495-1122577b-c535-4000-9e3a-2f72fe9ec21e.png)

</details>

<details>
<summary>Record in Reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/181593639-789f9dae-c19b-4f70-a21c-bf2f3c3118cb.png)

</details>

<details>
<summary>Delivery report (facility delivery) created.</summary>

![image](https://user-images.githubusercontent.com/94494491/181593921-05dad5a1-9c5a-4c52-89e8-7e0860c4cee7.png)

</details>

<details>
<summary>Record in reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/181594078-88a9215a-c59e-4717-9ab6-fd1c06985112.png)

</details>

<details>
<summary>Targets updated.</summary>

![image](https://user-images.githubusercontent.com/94494491/181594190-57fd0f45-6e89-4ae8-932b-722c46133706.png)

</details>

---

### **Pregnancy Workflow for "Charlotte" - Created using SMS**

**User:** CHW
**Config:** Standard
 **Environment:** gamma-cht
**Platform:** WebApp 
**Browser:** Chrome

<details>
<summary>New person created (N form).</summary>

![image](https://user-images.githubusercontent.com/94494491/181594553-d107b8d8-2e4a-4c70-80e8-2da481f64c52.png)
![image](https://user-images.githubusercontent.com/94494491/181594642-d902ced6-8df1-4965-9970-666e9c2cf9bb.png)
![image](https://user-images.githubusercontent.com/94494491/181594744-145ea56b-7f72-4170-b444-b4f2e436ecb4.png)

</details>

<details>
<summary>Pregnancy registered (P form).</summary>

![image](https://user-images.githubusercontent.com/94494491/181595632-faf09fba-b5bb-46ba-9ef7-9b2d7ade0905.png)
![image](https://user-images.githubusercontent.com/94494491/181595817-c548eb85-b490-410b-ba11-e460f9e579cc.png)

</details>

<details>
<summary>Record in reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/181595774-3a3637be-2cb2-4da2-af26-1ae17b3d2739.png)

</details>

<details>
<summary>Targets updated</summary>

![image](https://user-images.githubusercontent.com/94494491/181595917-76e19c74-1d3f-426d-ad37-3768b0e7bcc1.png)

</details>

<details>
<summary>Pregnancy visit created (web app).</summary>

![image](https://user-images.githubusercontent.com/94494491/181596103-3c0efbbb-548f-4c25-a733-17013368c3cc.png)

</details>

<details>
<summary>Record in reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/181596299-231c46ff-4389-426b-809d-4d6650208845.png)

</details>

<details>
<summary>Pregnancy visit created (V form) - 4 visits created to see a different card updated in targets.</summary>

![image](https://user-images.githubusercontent.com/94494491/181596804-9da4993d-c808-4d47-9525-95981b28f297.png)
![image](https://user-images.githubusercontent.com/94494491/181596896-8b9912c8-e3b8-4d80-b26a-3e35a96960ca.png)

</details>

<details>
<summary>Record in reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/181597039-cd5132eb-d588-4044-bd30-c76cc40578f0.png)

</details>

<details>
<summary>Delivery report (facility delivery) created (D form).</summary>

![image](https://user-images.githubusercontent.com/94494491/181597522-1d0d4467-a17b-44bb-b698-e35d6486c91c.png)
![image](https://user-images.githubusercontent.com/94494491/181597765-1f52b501-91cd-4604-a1d0-0417a3e7d559.png)

</details>

<details>
<summary>Record in reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/181597945-ee569da0-5cfc-4b05-a0f0-2d7b2e368f90.png)

</details>

<details>
<summary>Targets updated.</summary>

![image](https://user-images.githubusercontent.com/94494491/181597993-688dc3bf-b152-4b2d-9a6e-b05643caaa28.png)

</details>
